# Generated by Django 4.2.6 on 2023-10-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome do Personagem', max_length=100)),
                ('midia', models.CharField(default='Qual o filme/serie/livro', max_length=100)),
                ('profissao', models.CharField(default='Profissão do Personagem', max_length=100)),
                ('sobre', models.TextField(default='Resumo do Filme', max_length=700)),
                ('foto', models.ImageField(default='default_capa.jpg', upload_to='avatar')),
            ],
            options={
                'verbose_name': 'Nerd',
                'verbose_name_plural': 'Nerds',
            },
        ),
    ]
